import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

smtpServer = 'smtp.gmail.com'
smtpPort = 587

'''
Will try to implement google authentication, but for now will use app passwords generated by google account
https://myaccount.google.com/apppasswords
'''

# Get Gmail credentials
sender = input("Enter your Gmail address: ")
password = input("Enter your Gmail password: ")

# Establishing a connection to SMTP server with TLS encryption
server = smtplib.SMTP(smtpServer, smtpPort)
server.starttls()

try:
    server.login(sender, password)
    
    # Header
    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = input("Enter recipient's email address: ")
    msg['Subject'] = input("Enter email subject: ")
    
    # Message
    message_text = input("Enter email message: ")
    msg.attach(MIMEText(message_text, 'plain'))  # Attaching
    
    # Attachments
    choice = input("Type (1) if you would like to include an image\nType (2) if you don't want to include an Image: ")
    if int(choice) == 1:
        filename = input("Enter Image filename: ")
        with open(filename, 'rb') as f:
            attachment = f.read()
    else:
        pass

    p = MIMEBase('application', 'octet-stream')  # Processing attachment
    p.set_payload(attachment)

    encoders.encode_base64(p)
    p.add_header('Content-Disposition', f'attachment; filename={filename}')
    msg.attach(p)
    
    server.sendmail(sender, msg['To'], msg.as_string())
    print("Email sent successfully!")
except smtplib.SMTPAuthenticationError:
    print("Failed to authenticate. Please check your Gmail credentials.")
finally:
    server.quit()
